name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

    # # (Optional) Build Docker image or other build-related tasks
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # # Log in to Docker Hub (optional, only if needed for Docker-related tasks)
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # # (Optional) Build and push Docker image
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: <DOCKER_USERNAME>/basicapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build # Only runs after the 'build' job has completed

    steps:
      # Checkout the code again (if not cached)
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Ansible and sshpass
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      # Deploy the html and css files using Ansible
      - name: Deploy with Ansible
        run: |
          chmod 400 networkingEC2InstanceKeyPair.pem
          ansible-playbook -i inventory.ini ansible-playbook.yml
