name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code again (if not cached)
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Ansible and sshpass
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      # Deploy the html and css files using Ansible
      - name: Deploy with Ansible
        run: |
          ansible-playbook -i inventory.ini ansible-playbook.yml
